# Generated by Django 5.2.3 on 2025-06-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(choices=[('FlankerChallenge', 'Flanker Challenge'), ('BART', 'BART'), ('CAN', 'Connect Alphabet & Numbers'), ('Stroop', 'Stroop Test'), ('WYR', 'Would You Rather')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('raw_game_data', models.JSONField(blank=True, null=True)),
                ('flanker_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('flanker_correct_count', models.IntegerField(blank=True, null=True)),
                ('flanker_total_rounds', models.IntegerField(blank=True, null=True)),
                ('bart_total_cash', models.IntegerField(blank=True, null=True)),
                ('bart_avg_pumps', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bart_unpopped_balloons', models.IntegerField(blank=True, null=True)),
                ('bart_pumps_on_unpopped_balloons', models.IntegerField(blank=True, null=True)),
                ('can_final_time', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('can_total_elements', models.IntegerField(blank=True, null=True)),
                ('stroop_avg_congruent_rt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stroop_avg_incongruent_rt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stroop_congruent_errors', models.IntegerField(blank=True, null=True)),
                ('stroop_incongruent_errors', models.IntegerField(blank=True, null=True)),
                ('stroop_interference_time', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stroop_interference_errors', models.IntegerField(blank=True, null=True)),
                ('wyr_avg_response_time', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('wyr_impulsive_count', models.IntegerField(blank=True, null=True)),
                ('wyr_moderate_count', models.IntegerField(blank=True, null=True)),
                ('wyr_too_slow_count', models.IntegerField(blank=True, null=True)),
                ('wyr_individual_responses', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
