# Generated by Django 5.2.3 on 2025-06-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game_name',
            field=models.CharField(choices=[('RTT', 'Reaction Time Test'), ('FlankerChallenge', 'Flanker Challenge'), ('BART', 'BART'), ('CAN', 'Connect Alphabet & Numbers'), ('Stroop', 'Stroop Test'), ('WYR', 'Would You Rather')], max_length=50),
        ),
    ]
