# Generated by Django 5.2.3 on 2025-06-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gamescore_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='flanker_avg_reaction_time',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='participant_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
