# Generated by Django 5.2.3 on 2025-06-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamescore_flanker_avg_reaction_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game_name',
            field=models.CharField(choices=[('RTT', 'Reaction Time Test'), ('FC', 'Flanker Challenge'), ('BART', 'BART'), ('CAN', 'Connect Alphabet & Numbers'), ('STROOP', 'Stroop Test'), ('WYR', 'Would You Rather')], max_length=50),
        ),
    ]
