# Generated by Django 5.2.3 on 2025-06-29 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_gamescore_game_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamescore',
            options={},
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='stroop_avg_congruent_rt',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='stroop_avg_incongruent_rt',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='stroop_congruent_errors',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='stroop_incongruent_errors',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='stroop_interference_errors',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='stroop_interference_time',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='wyr_avg_response_time',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='wyr_impulsive_count',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='wyr_individual_responses',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='wyr_moderate_count',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='wyr_too_slow_count',
        ),
        migrations.AddField(
            model_name='gamescore',
            name='rtt_average_reaction_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='rtt_total_rounds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='stroop_avg_rt_congruent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='stroop_avg_rt_incongruent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='stroop_correct_congruent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='stroop_correct_incongruent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='stroop_total_congruent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='stroop_total_incongruent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='bart_avg_pumps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='can_final_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='flanker_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='flanker_avg_reaction_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='game_name',
            field=models.CharField(choices=[('RTT', 'RTT'), ('FC', 'FC'), ('BART', 'BART'), ('CAN', 'CAN'), ('STROOP', 'STROOP')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
